### ISSUE TITLE
Does not work with utc + 7

### ISSUE THREAD

**Issue by champseo2017** [mikeham98/react-awesome-calendar#1]
Event day Does not work with utc + 7
![image](https://user-images.githubusercontent.com/32265715/100137738-7a467080-2ebf-11eb-8ecb-554da1c48b01.png)
@mikeham98

**Comment by mikeham98** [comment]
Thanks for your comment. I’ll try and look into this asap.

**Comment by andygmorris** [comment]
Hi Mike, I work with Champ who reported this issue to you. Let me try and explain a bit more about what we've seen. An example scenario is a good way to begin. Let's say there's an appointment scheduled from 1600hrs to 0800hrs the following day, the calendar seems to think that from 0000hrs through to 0800hrs there's no appointment. Another person that woks with Champ has given me this screenshot (with a specific example). One thing to note is that we're using UTC+7 (for ICT) time, which could contribute to the issue. Perhaps the details and screenshot will help. If you're able to identify and fix the issue, we'd really appreciate that. Thanks in advance for your efforts.

![event_calendar_awesome_issue](https://user-images.githubusercontent.com/951393/100327148-73be1300-2ffd-11eb-9e68-6a3598c19abf.png)

**Comment by mikeham98** [comment]
Thanks for your detailed explanation @andygmorris. I'll try and find some time today to look into this, if not I should be able to fix it over the weekend. Thank you for your patience :D

**Comment by mikeham98** [comment]
I've managed to fix the issue locally, I'm going to run a few tests and check everything works as expected. Then I'll create a new release :D

**Comment by mikeham98** [comment]
From fixing this, a couple of other bugs have come about. I'll likely need a few days to fix it, sorry for any inconvenience caused!

**Comment by andygmorris** [comment]
Good luck Mike. Thank you for both the effort and the update.

**Comment by mikeham98** [comment]
Thank you for your patience. I've just released v1.0.12 which should fix this issue. Let me know if there are any problems :D

**Comment by andygmorris** [comment]
Mike, thank you for your efforts. We will give your new release a spin this week and report back.

**Comment by andygmorris** [comment]
Mike. Good news. The patched version works as expected. This case can be closed now. Thank you very much for your support.

**Comment by champseo2017** [comment]
Thank you very much @mikeham98  It works excellent.

**Comment by andygmorris** [comment]
Hi @mikeham98 - We may have a regression. What do you think could be causing that?

![afternoon_event_bug1](https://user-images.githubusercontent.com/951393/100579605-1258b580-3317-11eb-9386-33b7f1e000b4.png)
![afternoon_event_bug2](https://user-images.githubusercontent.com/951393/100579618-15ec3c80-3317-11eb-97b5-dbf1920affa7.png)

**Comment by mikeham98** [comment]
Ah no, sorry about that! I'll attempt to create a new release today with the fix :D

**Comment by mikeham98** [comment]
I've found the issue, it might take a bit of time to fix, its a similar sort of issue to the one we had the other day. I'll hopefully have something released Tuesday/Wednesday. Sorry about this, I hope it's not holding up any deadlines!

**Comment by mikeham98** [comment]
I had a bit of time in my lunch break to fix this. I've just released v1.0.13 this should resolve the issue :D

**Comment by andygmorris** [comment]
Thanks @mikeham98 we'll give that a spin and drop some feedback later today. Appreciated.

**Comment by andygmorris** [comment]
Hi @mikeham98 - our developers tested multiple scenarios and wanted to report them for your attention. Of course, we know you're busy. Please let us know when you've had time to adjust the code according to the challenges. Thanks for your time on this plugin. 4 images attached (ordered, 1-4).

![1-testplan](https://user-images.githubusercontent.com/951393/100707393-3088e900-33dd-11eb-806a-f847879871a9.png)
![2-fourday-aftnoon-beforenoon-bug](https://user-images.githubusercontent.com/951393/100707406-3383d980-33dd-11eb-9b44-23c07c18b3d2.png) scr
![3-threeday-afternoon-aftnoon-bug](https://user-images.githubusercontent.com/951393/100707410-34b50680-33dd-11eb-9bd1-150f23e43a2a.png)
![4-fourday-aftnoon-midnight-bug](https://user-images.githubusercontent.com/951393/100707412-35e63380-33dd-11eb-8a3d-9d53ccd1e230.png)

**Comment by mikeham98** [comment]
Hi @andygmorris, sorry to hear it’s still not working as expected. I think I know where the issue lies, it’s to do with the calculation of the number of days between two events. I can spend sometime today/tomorrow evening to look at this. When I do, I’ll write up some automated unit tests to ensure it all works according to your test plan 😊

**Comment by mikeham98** [comment]
Using your test data I've written up unit tests for the function that's causing this issue. Some of the tests failed to begin with ("to" dates set to midnight were showing an event on that day, however they should instead show in the previous day running up to 24hrs) along with your failing tests (only when I set my computers timezone to +7hrs). I've since fixed this, ran all the tests in my timezone as well as +7hrs, and they all pass. Therefore events now appear correctly in the calendar monthly view. There is however one slight issue with the daily view when rendering events. I need to take a further look into this, I'll try and fix it tonight/tomorrow. Thank you for your patience :D

**Comment by mikeham98** [comment]
Just published v1.0.14 :D

**Comment by andygmorris** [comment]
@mikeham98 Good news. All tested ok at our end. Thanks very much (again) for your efforts.

**Comment by mikeham98** [comment]
@andygmorris @champseo2017 That's great it's all working now! Thank you for helping me solve this issue :D
