### ISSUE TITLE
Calendar Links Not Clickable in Safari

### ISSUE THREAD

**Issue by andygmorris** [mikeham98/react-awesome-calendar#2]
![anb_ios](https://user-images.githubusercontent.com/951393/102048758-4b625100-3e12-11eb-8c64-127a4b7839b3.jpg)

Hi Mike, we have an issue with the calendar. The links aren't clickable when using Safari on iPhone, iPad or even macOS, so we can't select the entries shown (on the example screenshot). These links work fine in Chrome, but not Safari. Any idea what could be blocking them from being clickable?

**Comment by andygmorris** [comment]
Hi Mike, any chance you could take a look at this issue for us?

**Comment by andygmorris** [comment]
@mikeham98 mentioned to get your attention  :-)

**Comment by mikeham98** [comment]
Hi @andygmorris thanks for mentioning me, I think my email notifications aren’t set up properly, so I only saw this upon your mention. I will aim to look into this today :)

**Comment by mikeham98** [comment]
@andygmorris sorry for the late reply, had a busy week. Would you be able to further explain what the issue is? When you say "link" are you referring to the event that appears in the calendar? What are you expecting to happen?

FYI I noticed that in your screenshot (as well as when I tested on Safari) events that span multiple days aren't lining up correctly side-by-side. I've now fixed this, I will create a release once this issue has been resolved.

Before:
<img width="818" alt="Screenshot 2020-12-17 at 23 10 26" src="https://user-images.githubusercontent.com/37596481/102554616-0f064d80-40bd-11eb-8a22-d66744a6671b.png">

After:
<img width="813" alt="Screenshot 2020-12-17 at 23 10 07" src="https://user-images.githubusercontent.com/37596481/102554583-0281f500-40bd-11eb-9dbd-58c866d442f1.png">

Many thanks! :D

**Comment by andygmorris** [comment]
@mikeham98 Thanks for the feedback and the for the fixing the issue that we didn't even mention ;-) I will create a video of the Safari issue and share that with you later (in a few hours).

**Comment by andygmorris** [comment]
Hi @mikeham98 I've attached a zip file containing 3 screen recordings.

#01 = Using Google Chrome on macOS desktop. Working as epected: we can click the 25-DEC date and get to the day view.

#02 = Using Safari on macOS desktop. We can't click the date, or anywhere else.

#03 = Using Safari on iPhone 11 Pro (macOS Xcode Simulator). We can't click the date, or anywhere else.

The demo on the Simulator gives us the same result when we use a real (in-hand) iPhone.

Something in Safari is blocking the event/date from being clickable.

Please let us know if we can help further to identify this issue, whether it be code, or our environments.

[Demonstration.zip](https://github.com/mikeham98/react-awesome-calendar/files/5713224/Demonstration.zip)

**Comment by mikeham98** [comment]
@andygmorris sorry for the late reply, I've tested this on Safari on both Mac and iPhone however I can't replicate the issue. Would you be able to send me the props that you are passing to the calendar component? Thanks :D

**Comment by andygmorris** [comment]
@mikeham98 - File attached. Developer says "I think browserHistory.push in ios is not working". Any advice appreciated.
[mike.txt](https://github.com/mikeham98/react-awesome-calendar/files/5722251/mike.txt)

**Comment by mikeham98** [comment]
@andygmorris I believe this is an issue with your codebase, the browser history object is not used within this library and it is used within your handleOnChange. It could be that there is a bug within your configuration of the browser history.

**Comment by andygmorris** [comment]
@mikeham98 Thanks for taking a look Mike. I'll hand it back over to our Dev to see if they figure it out.

**Comment by andygmorris** [comment]
@mikeham98 This issue was resolved, apologies for not mentioning it sooner. It was an error at our end, not yours. This issue can be closed.

**Comment by mikeham98** [comment]
@andygmorris no worries at all! I still need to release the fix which misaligns events spanning multiple days on safari. I’ll aim to release it this week
